# Generated by Django 6.0.6 on 2026-07-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "completed"),
                    ("HALTED", "halted"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
