# Generated by Django 6.0.6 on 2026-07-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_task", "0002_tasks_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
